# Generated by Django 5.0.7 on 2025-07-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="extracted_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
