# Generated by Django 5.2.4 on 2025-07-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifier", "0002_uploadeddocument_extracted_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="document_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="verification_status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
