# Generated by Django 5.2.4 on 2025-07-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifier", "0003_uploadeddocument_document_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="dob",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="document_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
