# Generated by Django 5.2.4 on 2025-07-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifier", "0004_uploadeddocument_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadeddocument",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
