# Generated by Django 5.2.4 on 2025-07-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifier", "0005_alter_uploadeddocument_dob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadeddocument",
            name="document_number",
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="passport_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="uploadeddocument",
            name="dob",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
